import { useState } from "react";
import { Loader2, ChevronDown, ChevronUp } from "lucide-react";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/ui/card";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/ui/collapsible";
import { Progress } from "@/ui/progress";
import { VirtualizedCodeViewer } from "@/ui/virtualized-code-viewer";
import { useJobDetailsContext } from "../../_contexts/job-details-context";

import { getStreamingProgressValue } from "../../utils";

export function JobDetailsResponseSection() {
  const { job, responseContent, parsedMetadata } = useJobDetailsContext();
  const [isResponseOpen, setIsResponseOpen] = useState(false);

  return (
    <Card>
      <Collapsible open={isResponseOpen} onOpenChange={setIsResponseOpen}>
        <CollapsibleTrigger asChild>
          <CardHeader className="py-4 px-6 cursor-pointer hover:bg-accent/30 transition-all duration-200 rounded-t-xl group">
            <div className="flex justify-between items-center">
              <div>
                <CardTitle className="text-sm font-semibold flex items-center gap-2 group-hover:text-foreground/80 transition-colors">
                  {job.taskType === "implementation_plan" &&
                  parsedMetadata?.showPureContent === true ? (
                    <>
                      <span>Content</span>
                      {job.status === "running" && parsedMetadata?.isStreaming && (
                        <div className="flex items-center gap-1">
                          <Loader2 className="h-3 w-3 animate-spin" />
                          <span className="text-xs">Live Updates</span>
                        </div>
                      )}
                    </>
                  ) : (
                    <span>Response</span>
                  )}
                </CardTitle>
                <CardDescription className="text-sm text-muted-foreground/80 mt-1">
                  Output generated by the AI model
                </CardDescription>
              </div>
              <div className="flex items-center gap-2">
                {isResponseOpen ? <ChevronUp className="h-5 w-5 text-muted-foreground group-hover:text-foreground transition-colors" /> : <ChevronDown className="h-5 w-5 text-muted-foreground group-hover:text-foreground transition-colors" />}
              </div>
            </div>
          </CardHeader>
        </CollapsibleTrigger>

        <CollapsibleContent>
          <CardContent className="pt-0">
            {/* Show progress bar for streaming jobs */}
            {job.status === "running" && parsedMetadata?.isStreaming ? (
              <div className="mb-3">
                <Progress
                  value={
                    // Calculate progress with unified handling for implementation plans
                    job.taskType === "implementation_plan"
                      ? getStreamingProgressValue(
                          job.metadata,
                          job.startTime,
                          job.maxOutputTokens
                        )
                      : parsedMetadata?.responseLength &&
                          parsedMetadata?.estimatedTotalLength
                        ? Math.min(
                            (Number(parsedMetadata.responseLength) /
                              Number(parsedMetadata.estimatedTotalLength)) *
                              100,
                            97
                          )
                        : Math.min(
                            Math.floor(
                              (Date.now() - (job.startTime || Date.now())) / 150
                            ),
                            90
                          )
                  }
                  className="h-1 mb-2"
                />
                <div className="flex justify-between items-center text-xs text-muted-foreground">
                  <div className="flex items-center gap-2">
                    <Loader2 className="h-3 w-3 animate-spin text-info" />
                    <span className="text-info font-medium">
                      Streaming in progress...
                    </span>
                  </div>
                  <div className="flex items-center gap-2">
                    {parsedMetadata?.responseLength ? (
                      <span>
                        {Math.floor(Number(parsedMetadata.responseLength) / 1024)} KB received
                      </span>
                    ) : null}
                    {typeof parsedMetadata?.streamProgress === "number" && (
                      <span>{Math.floor(parsedMetadata.streamProgress)}% complete</span>
                    )}
                  </div>
                </div>
              </div>
            ) : null}

            <VirtualizedCodeViewer
              content={responseContent}
              height="60vh"
              showCopy={true}
              copyText={job.taskType === "implementation_plan" ? "Copy content" : "Copy response"}
              showContentSize={true}
              isLoading={job.status === "running" && Boolean(parsedMetadata?.isStreaming)}
              placeholder="No response content available"
              className={
                job.taskType === "implementation_plan" &&
                parsedMetadata?.showPureContent === true
                  ? job.status === "running" && parsedMetadata?.isStreaming
                    ? "border-info/60 bg-info/5"
                    : "border-success/60 bg-success/5"
                  : job.taskType === "path_finder" || job.taskType === "regex_pattern_generation"
                    ? "border-border/60 bg-slate-50/50 dark:bg-slate-900/50"
                    : undefined
              }
              loadingIndicator={
                <div className="flex items-center justify-center h-full">
                  <div className="flex items-center gap-2">
                    <Loader2 className="h-4 w-4 animate-spin text-info" />
                    <span className="text-sm text-info">Streaming response...</span>
                  </div>
                </div>
              }
            />
          </CardContent>
        </CollapsibleContent>
      </Collapsible>
    </Card>
  );
}
