import { useState } from "react";
import { Loader2, ClipboardCopy, FileCode, ChevronDown, ChevronUp } from "lucide-react";

import { type BackgroundJob } from "@/types/session-types";
import { Button } from "@/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/ui/card";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/ui/collapsible";
import { Progress } from "@/ui/progress";
import { ScrollArea } from "@/ui/scroll-area";
import { useNotification } from "@/contexts/notification-context";

import { getStreamingProgressValue } from "../../utils";

interface JobDetailsResponseSectionProps {
  job: BackgroundJob;
  responseContent: string;
}

export function JobDetailsResponseSection({
  job,
  responseContent,
}: JobDetailsResponseSectionProps) {
  const [isResponseOpen, setIsResponseOpen] = useState(true);
  const [showFullResponse, setShowFullResponse] = useState(false);
  const { showNotification } = useNotification();
  
  const PREVIEW_CHARS = 1000;
  const isLongContent = responseContent.length > PREVIEW_CHARS;
  const displayContent = showFullResponse || !isLongContent 
    ? responseContent 
    : responseContent.substring(0, PREVIEW_CHARS) + "...";

  return (
    <Card>
      <Collapsible open={isResponseOpen} onOpenChange={setIsResponseOpen}>
        <CollapsibleTrigger asChild>
          <CardHeader className="py-4 px-6 cursor-pointer hover:bg-accent/30 transition-all duration-200 rounded-t-xl group">
            <div className="flex justify-between items-center">
              <div>
                <CardTitle className="text-base font-semibold flex items-center gap-2 group-hover:text-foreground/80 transition-colors">
                  {job.taskType === "implementation_plan" &&
                  job.metadata?.showPureContent === true ? (
                    <>
                      <span>Content</span>
                      {job.status === "running" && job.metadata?.isStreaming && (
                        <div className="flex items-center gap-1">
                          <Loader2 className="h-3 w-3 animate-spin" />
                          <span className="text-xs">Live Updates</span>
                        </div>
                      )}
                    </>
                  ) : (
                    <span>Response</span>
                  )}
                </CardTitle>
                <CardDescription className="text-sm text-muted-foreground/80 mt-1">
                  Output generated by the AI model
                </CardDescription>
              </div>
              <div className="flex items-center gap-2">
                {job.taskType === "implementation_plan" && job.response && (
                  <Button
                    size="sm"
                    variant="outline"
                    className="text-xs"
                    onClick={(e) => {
                      e.stopPropagation();
                      void navigator.clipboard.writeText(job.response || "");
                      showNotification({
                        title: "Copied to clipboard",
                        message: "Implementation plan content copied to clipboard",
                        type: "success",
                        duration: 2000,
                      });
                    }}
                  >
                    <ClipboardCopy className="h-3 w-3 mr-1" />
                    Copy content
                  </Button>
                )}
                {isResponseOpen ? <ChevronUp className="h-5 w-5 text-muted-foreground group-hover:text-foreground transition-colors" /> : <ChevronDown className="h-5 w-5 text-muted-foreground group-hover:text-foreground transition-colors" />}
              </div>
            </div>
          </CardHeader>
        </CollapsibleTrigger>

        <CollapsibleContent>
          <CardContent className="pt-0">
            {/* Show progress bar for streaming jobs */}
            {job.status === "running" && job.metadata?.isStreaming && (
              <div className="mb-3">
                <Progress
                  value={
                    // Calculate progress with unified handling for implementation plans
                    job.taskType === "implementation_plan"
                      ? getStreamingProgressValue(
                          job.metadata,
                          job.startTime,
                          job.maxOutputTokens
                        )
                      : job.metadata.responseLength &&
                          job.metadata.estimatedTotalLength
                        ? Math.min(
                            (job.metadata.responseLength /
                              job.metadata.estimatedTotalLength) *
                              100,
                            97
                          )
                        : Math.min(
                            Math.floor(
                              (Date.now() - (job.startTime || Date.now())) / 150
                            ),
                            90
                          )
                  }
                  className="h-1 mb-2"
                />
                <div className="flex justify-between items-center text-xs text-muted-foreground">
                  <div className="flex items-center gap-2">
                    <Loader2 className="h-3 w-3 animate-spin text-info" />
                    <span className="text-info font-medium">
                      Streaming in progress...
                    </span>
                  </div>
                  <div className="flex items-center gap-2">
                    {job.metadata.responseLength && (
                      <span>
                        {Math.floor(job.metadata.responseLength / 1024)} KB received
                      </span>
                    )}
                    {typeof job.metadata.streamProgress === "number" && (
                      <span>{Math.floor(job.metadata.streamProgress)}% complete</span>
                    )}
                  </div>
                </div>
              </div>
            )}

              <div>
                <ScrollArea className={`${showFullResponse ? "max-h-[70vh]" : "max-h-[40vh]"}`}>
                  <pre
                    className={`whitespace-pre-wrap font-mono text-balance w-full text-foreground ${
                      job.taskType === "implementation_plan" &&
                      job.metadata?.showPureContent === true
                        ? job.status === "running" && job.metadata?.isStreaming
                          ? "text-xs p-6 bg-info/10 border border-info/30 text-info rounded-md animate-pulse"
                          : "text-xs p-6 bg-success/15 border border-success/30 text-success rounded-md"
                        : job.taskType === "implementation_plan"
                          ? "text-xs p-6 bg-muted/20 rounded-md"
                          : "text-xs"
                    }`}
                  >
                    {displayContent}
                  </pre>
                </ScrollArea>
                {isLongContent && (
                  <Button
                    variant="ghost"
                    size="sm"
                    className="mt-3 text-xs"
                    onClick={() => setShowFullResponse(!showFullResponse)}
                  >
                    {showFullResponse ? "Show Less" : "Show More"}
                  </Button>
                )}
              </div>
          </CardContent>
        </CollapsibleContent>
      </Collapsible>
    </Card>
  );
}
