/**
 * Task settings type definitions
 */

export interface TaskModelSettings {
  model: string;
  maxTokens: number;
  temperature: number;
}

/**
 * TaskSettings interface using camelCase for all keys
 * These keys must match the camelCase keys generated by snake_to_camel_case in settings_commands.rs
 */
export interface TaskSettings {
  pathFinder: TaskModelSettings;
  transcription: TaskModelSettings; // maps to voice_transcription
  regexGeneration: TaskModelSettings;
  regexSummaryGeneration: TaskModelSettings;
  pathCorrection: TaskModelSettings;
  textImprovement: TaskModelSettings;
  textCorrectionPostTranscription: TaskModelSettings;
  voiceCorrection: TaskModelSettings;
  taskEnhancement: TaskModelSettings;
  guidanceGeneration: TaskModelSettings;
  implementationPlan: TaskModelSettings;
  genericLlmStream: TaskModelSettings;
  generateDirectoryTree: TaskModelSettings;
  streaming: TaskModelSettings;
  unknown: TaskModelSettings;
}
