/**
 * Generated TypeScript definitions for Tauri commands
 * DO NOT EDIT DIRECTLY - This file is generated by generate-tauri-types.mjs
 */

// Command interface definitions

// Commands from app_commands
export interface Get_database_info_commandArgs {
}


// Commands from auth_commands
export interface Exchange_and_store_firebase_tokenArgs {
  firebase_id_token: string;
}

export interface Get_user_info_with_app_jwtArgs {
  app_token: string;
}

export interface Set_in_memory_tokenArgs {
  token: string;
}

export interface Clear_in_memory_tokenArgs {
}


// Commands from db_commands
export interface Db_execute_queryArgs {
  sql: string;
  params: Array<any>;
}

export interface Db_select_queryArgs {
  sql: string;
  params: Array<any>;
}

export interface Db_execute_transactionArgs {
  operations: Array<any>;
}

export interface Db_table_existsArgs {
  table_name: string;
}


// Commands from fetch_handler_command
export interface Handle_fetch_requestArgs {
  args: any;
}

export interface Invoke_fetch_handlerArgs {
  url: string;
  method: string;
  headers: any | null;
  body: string | null;
}

export interface Invoke_stream_handlerArgs {
  url: string;
  method: string;
  headers: any | null;
  body: string | null;
  on_chunk: any;
}


// Commands from file_system_commands
export interface List_files_commandArgs {
  args: any;
}

export interface Create_directory_commandArgs {
  args: any;
}

export interface Read_file_content_commandArgs {
  args: any;
}

export interface Write_file_content_commandArgs {
  args: any;
}

export interface Create_unique_filepath_commandArgs {
  args: any;
}

export interface Delete_file_commandArgs {
  args: any;
}

export interface Move_file_commandArgs {
  args: any;
}

export interface Get_app_data_directory_commandArgs {
}

export interface Get_temp_dir_commandArgs {
}


// Commands from generic_task_commands
export interface Generic_llm_stream_commandArgs {
  args: any;
}

export interface Enhance_task_description_commandArgs {
  args: any;
}


// Commands from guidance_commands
export interface Generate_guidance_commandArgs {
  args: any;
}


// Commands from implementation_plan_commands
export interface Create_implementation_plan_commandArgs {
  args: any;
}

export interface Read_implementation_plan_commandArgs {
  args: any;
}


// Commands from job_commands
export interface Update_job_cleared_status_commandArgs {
  job_id: string;
  cleared: boolean;
}

export interface Get_background_job_by_id_commandArgs {
  job_id: string;
}

export interface Clear_job_history_commandArgs {
  days_to_keep: number;
}

export interface Get_active_jobs_commandArgs {
}

export interface Delete_background_job_commandArgs {
  args: any;
}

export interface Cancel_background_job_commandArgs {
  args: any;
}

export interface Cancel_session_jobs_commandArgs {
  args: any;
}


// Commands from path_finding_commands
export interface Find_relevant_files_commandArgs {
  args: any;
}

export interface Create_generate_directory_tree_job_commandArgs {
  args: any;
}


// Commands from regex_commands
export interface Generate_regex_commandArgs {
  args: any;
}


// Commands from text_commands
export interface Improve_text_commandArgs {
  args: any;
}

export interface Correct_text_post_transcription_commandArgs {
  args: any;
}


// Commands from voice_commands
export interface Create_transcription_job_commandArgs {
  args: any;
}

export interface Correct_transcription_commandArgs {
  args: any;
}

export interface Transcribe_audio_direct_commandArgs {
  args: any;
}


// Tauri invoke function type
export type TauriInvoke = {
  "get_database_info_command": () => Promise<any>;
  "exchange_and_store_firebase_token": (args: Exchange_and_store_firebase_tokenArgs) => Promise<any>;
  "get_user_info_with_app_jwt": (args: Get_user_info_with_app_jwtArgs) => Promise<any>;
  "set_in_memory_token": (args: Set_in_memory_tokenArgs) => Promise<any>;
  "clear_in_memory_token": () => Promise<any>;
  "db_execute_query": (args: Db_execute_queryArgs) => Promise<any>;
  "db_select_query": (args: Db_select_queryArgs) => Promise<any>;
  "db_execute_transaction": (args: Db_execute_transactionArgs) => Promise<any>;
  "db_table_exists": (args: Db_table_existsArgs) => Promise<any>;
  "handle_fetch_request": (args: Handle_fetch_requestArgs) => Promise<any>;
  "invoke_fetch_handler": (args: Invoke_fetch_handlerArgs) => Promise<any>;
  "invoke_stream_handler": (args: Invoke_stream_handlerArgs) => Promise<any>;
  "list_files_command": (args: List_files_commandArgs) => Promise<any>;
  "create_directory_command": (args: Create_directory_commandArgs) => Promise<any>;
  "read_file_content_command": (args: Read_file_content_commandArgs) => Promise<any>;
  "write_file_content_command": (args: Write_file_content_commandArgs) => Promise<any>;
  "create_unique_filepath_command": (args: Create_unique_filepath_commandArgs) => Promise<any>;
  "delete_file_command": (args: Delete_file_commandArgs) => Promise<any>;
  "move_file_command": (args: Move_file_commandArgs) => Promise<any>;
  "get_app_data_directory_command": () => Promise<any>;
  "get_temp_dir_command": () => Promise<any>;
  "generic_llm_stream_command": (args: Generic_llm_stream_commandArgs) => Promise<any>;
  "enhance_task_description_command": (args: Enhance_task_description_commandArgs) => Promise<any>;
  "generate_guidance_command": (args: Generate_guidance_commandArgs) => Promise<any>;
  "create_implementation_plan_command": (args: Create_implementation_plan_commandArgs) => Promise<any>;
  "read_implementation_plan_command": (args: Read_implementation_plan_commandArgs) => Promise<any>;
  "update_job_cleared_status_command": (args: Update_job_cleared_status_commandArgs) => Promise<any>;
  "get_background_job_by_id_command": (args: Get_background_job_by_id_commandArgs) => Promise<any>;
  "clear_job_history_command": (args: Clear_job_history_commandArgs) => Promise<any>;
  "get_active_jobs_command": () => Promise<any>;
  "delete_background_job_command": (args: Delete_background_job_commandArgs) => Promise<any>;
  "cancel_background_job_command": (args: Cancel_background_job_commandArgs) => Promise<any>;
  "cancel_session_jobs_command": (args: Cancel_session_jobs_commandArgs) => Promise<any>;
  "find_relevant_files_command": (args: Find_relevant_files_commandArgs) => Promise<any>;
  "create_generate_directory_tree_job_command": (args: Create_generate_directory_tree_job_commandArgs) => Promise<any>;
  "generate_regex_command": (args: Generate_regex_commandArgs) => Promise<any>;
  "improve_text_command": (args: Improve_text_commandArgs) => Promise<any>;
  "correct_text_post_transcription_command": (args: Correct_text_post_transcription_commandArgs) => Promise<any>;
  "create_transcription_job_command": (args: Create_transcription_job_commandArgs) => Promise<any>;
  "correct_transcription_command": (args: Correct_transcription_commandArgs) => Promise<any>;
  "transcribe_audio_direct_command": (args: Transcribe_audio_direct_commandArgs) => Promise<any>;
};

// Strongly typed invoke function
export declare function invoke<T extends keyof TauriInvoke>(
  command: T,
  ...args: Parameters<TauriInvoke[T]>
): ReturnType<TauriInvoke[T]>;
