// STRIPE API IDEMPOTENCY REQUIREMENTS:
//
// All mutating Stripe API operations (POST requests) MUST include an `Idempotency-Key` header
// to ensure safe retry behavior and prevent duplicate operations in case of network failures
// or application restarts.
//
// IDEMPOTENCY KEY REQUIREMENTS:
// 1. Each distinct operation MUST have a unique idempotency key
// 2. Keys should be UUIDs or similar unique identifiers
// 3. Keys MUST be reused for retries of the same logical operation
// 4. Keys should NOT be reused across different operations
// 5. Idempotency keys expire after 24 hours in Stripe's system
//
// CURRENT IMPLEMENTATION STATUS:
// - ✅ This service now implements idempotency key handling
// - ✅ All mutating methods accept an idempotency_key parameter
// - ✅ BillingService generates unique UUIDs for each operation
// - Note: PaymentMethod::detach may need library-specific idempotency handling
//
// RECOMMENDED IMPLEMENTATION:
// ```rust
// pub async fn create_customer_with_idempotency(
//     &self,
//     idempotency_key: &str,  // Add this parameter
//     user_id: &Uuid,
//     email: &str,
//     name: Option<&str>
// ) -> Result<Customer, StripeServiceError> {
//     // Set idempotency key in request headers
//     // self.client.set_idempotency_key(idempotency_key);
//     // ... rest of implementation
// }
// ```
//
// CRITICAL FOR BILLING OPERATIONS:
// - Payment processing operations MUST be idempotent to prevent double charges
// - Credit purchase operations MUST be idempotent to prevent duplicate billing
// - Usage record reporting MUST be idempotent to prevent double billing
//
use crate::stripe_types::{self, *};
use reqwest::header::{HeaderMap, HeaderValue, AUTHORIZATION, CONTENT_TYPE};
use chrono::{DateTime, Utc};
use hmac::{Hmac, Mac};
use sha2::Sha256;
use std::collections::HashMap;
use uuid::Uuid;
use log::{debug, error, info, warn};
use hex;

#[derive(Debug, thiserror::Error)]
pub enum StripeServiceError {
    #[error("Stripe API error: {0}")]
    StripeApi(String),
    #[error("Webhook verification failed: {0}")]
    WebhookVerification(String),
    #[error("Invalid configuration: {0}")]
    Configuration(String),
    #[error("Payment processing error: {0}")]
    PaymentProcessing(String),
    #[error("Credit billing error: {0}")]
    CreditBilling(String),
}

type HmacSha256 = Hmac<Sha256>;


// Stripe Customer Portal Configuration Required:
// 1. Enable payment method management
// 2. Enable credit purchase and invoicing
// 3. Enable payment method updates
// 4. Enable invoice access
// 5. Set return URL to app billing page
// 6. Configure business branding

/// Stripe service for handling payment processing and credit-based billing
/// 
/// IMPORTANT: This service implements Stripe's idempotency requirements.
/// All mutating operations include idempotency keys to prevent:
/// - Duplicate payments
/// - Duplicate credit purchases  
/// - Duplicate usage records
/// - Data inconsistencies during retries
/// 
/// Idempotency keys are generated by the calling service (BillingService) as UUIDs.
#[derive(Clone)]
pub struct StripeService {
    webhook_secret: String,
    publishable_key: String,
    secret_key: String,
    http_client: reqwest::Client,
}

impl std::fmt::Debug for StripeService {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("StripeService")
            .field("webhook_secret", &"<redacted>")
            .field("publishable_key", &self.publishable_key)
            .finish()
    }
}

impl StripeService {
    pub fn new(secret_key: String, webhook_secret: String, publishable_key: String) -> Self {
        let http_client = reqwest::Client::new();
        
        Self {
            webhook_secret,
            publishable_key,
            secret_key,
            http_client,
        }
    }

    pub fn get_publishable_key(&self) -> &str {
        &self.publishable_key
    }

    /// Make a direct authenticated request to Stripe API with idempotency key
    async fn make_stripe_request_with_idempotency(
        &self,
        method: reqwest::Method,
        endpoint: &str,
        body: Option<serde_json::Value>,
        idempotency_key: &str,
    ) -> Result<serde_json::Value, StripeServiceError> {
        let url = format!("https://api.stripe.com/v1/{}", endpoint);
        
        let mut headers = HeaderMap::new();
        headers.insert(AUTHORIZATION, HeaderValue::from_str(&format!("Bearer {}", self.secret_key))
            .map_err(|_| StripeServiceError::Configuration("Invalid secret key format".to_string()))?);
        headers.insert(CONTENT_TYPE, HeaderValue::from_static("application/x-www-form-urlencoded"));
        headers.insert("Idempotency-Key", HeaderValue::from_str(idempotency_key)
            .map_err(|_| StripeServiceError::Configuration("Invalid idempotency key format".to_string()))?);
        headers.insert("Stripe-Version", HeaderValue::from_static("2023-10-16"));
        
        let mut request = self.http_client.request(method, &url).headers(headers);
        
        if let Some(body_data) = body {
            // Convert JSON to form-encoded data for Stripe API
            let form_data = self.json_to_form_data(body_data)?;
            request = request.body(form_data);
        }
        
        let response = request.send().await
            .map_err(|e| StripeServiceError::Configuration(format!("HTTP request failed: {}", e)))?;
        
        if !response.status().is_success() {
            let error_text = response.text().await
                .unwrap_or_else(|_| "Unknown error".to_string());
            return Err(StripeServiceError::Configuration(format!("Stripe API error: {}", error_text)));
        }
        
        let response_json: serde_json::Value = response.json().await
            .map_err(|e| StripeServiceError::Configuration(format!("Failed to parse response: {}", e)))?;
        
        Ok(response_json)
    }
    
    /// Convert JSON object to form-encoded data for Stripe API
    fn json_to_form_data(&self, json: serde_json::Value) -> Result<String, StripeServiceError> {
        fn flatten_object(obj: &serde_json::Value, prefix: &str, params: &mut Vec<(String, String)>) {
            match obj {
                serde_json::Value::Object(map) => {
                    for (key, value) in map {
                        let new_key = if prefix.is_empty() {
                            key.clone()
                        } else {
                            format!("{}[{}]", prefix, key)
                        };
                        flatten_object(value, &new_key, params);
                    }
                }
                serde_json::Value::Array(arr) => {
                    for (index, value) in arr.iter().enumerate() {
                        let new_key = format!("{}[{}]", prefix, index);
                        flatten_object(value, &new_key, params);
                    }
                }
                value => {
                    let string_value = match value {
                        serde_json::Value::String(s) => s.clone(),
                        serde_json::Value::Number(n) => n.to_string(),
                        serde_json::Value::Bool(b) => b.to_string(),
                        serde_json::Value::Null => return,
                        _ => return,
                    };
                    params.push((prefix.to_string(), string_value));
                }
            }
        }
        
        let mut params = Vec::new();
        flatten_object(&json, "", &mut params);
        
        let form_string = params
            .into_iter()
            .map(|(k, v)| format!("{}={}", urlencoding::encode(&k), urlencoding::encode(&v)))
            .collect::<Vec<_>>()
            .join("&");
        
        Ok(form_string)
    }

    /// Verify webhook signature with timestamp validation
    pub fn verify_webhook_signature(
        &self,
        payload: &str,
        signature: &str,
    ) -> Result<(), StripeServiceError> {
        let elements: Vec<&str> = signature.split(',').collect();
        let mut timestamp = "";
        let mut signatures = Vec::new();

        for element in elements {
            if let Some(t) = element.strip_prefix("t=") {
                timestamp = t;
            } else if let Some(s) = element.strip_prefix("v1=") {
                signatures.push(s);
            }
        }

        if timestamp.is_empty() || signatures.is_empty() {
            return Err(StripeServiceError::WebhookVerification(
                "Invalid signature format".to_string(),
            ));
        }

        // Validate timestamp to prevent replay attacks - reject webhooks older than 5 minutes
        let timestamp_int: i64 = timestamp.parse()
            .map_err(|e| StripeServiceError::WebhookVerification(format!("Invalid timestamp format: {}", e)))?;
        let now = chrono::Utc::now().timestamp();
        let time_diff = (now - timestamp_int).abs();
        
        if time_diff > 300 { // 5 minutes = 300 seconds
            return Err(StripeServiceError::WebhookVerification(
                format!("Webhook timestamp outside allowed window: webhook is {} seconds old (maximum 300 seconds allowed)", time_diff)
            ));
        }

        let signed_payload = format!("{}.{}", timestamp, payload);
        
        let mut mac = HmacSha256::new_from_slice(self.webhook_secret.as_bytes())
            .map_err(|e| StripeServiceError::WebhookVerification(format!("HMAC error: {}", e)))?;
        
        mac.update(signed_payload.as_bytes());
        let expected_signature = hex::encode(mac.finalize().into_bytes());

        for signature in signatures {
            if signature == expected_signature {
                return Ok(());
            }
        }

        Err(StripeServiceError::WebhookVerification(
            "Signature verification failed".to_string(),
        ))
    }

    /// Parse webhook event from payload
    pub fn parse_webhook_event(&self, payload: &str) -> Result<stripe_types::Event, StripeServiceError> {
        let event: stripe_types::Event = serde_json::from_str(payload)
            .map_err(|e| StripeServiceError::WebhookVerification(format!("Failed to parse event: {}", e)))?;
        Ok(event)
    }

    /// Construct and verify webhook event (combines signature verification and parsing)
    pub fn construct_event(
        &self,
        payload: &str,
        signature: &str,
    ) -> Result<stripe_types::Event, StripeServiceError> {
        self.verify_webhook_signature(payload, signature)?;
        self.parse_webhook_event(payload)
    }

    /// Process Stripe webhook event with idempotency key handling
    /// This method provides webhook event processing with built-in idempotency checks
    pub fn process_stripe_webhook_event(
        &self,
        event: &stripe_types::Event,
        idempotency_key: &str,
    ) -> Result<stripe_types::Event, StripeServiceError> {
        // Log the processing attempt with idempotency key
        info!("Processing Stripe webhook event {} (type: {}) with idempotency key: {}", 
              event.id, event.type_, idempotency_key);
        
        // The actual webhook processing is handled by the calling service
        // This method primarily serves as a validation and logging point
        // with idempotency key integration for future use
        
        // Validate event has required fields
        if event.id.is_empty() {
            return Err(StripeServiceError::WebhookVerification(
                "Event ID is missing".to_string(),
            ));
        }
        
        if event.type_.is_empty() {
            return Err(StripeServiceError::WebhookVerification(
                "Event type is missing".to_string(),
            ));
        }
        
        // Return the validated event for further processing
        Ok(event.clone())
    }

    /// Create or retrieve existing customer
    pub async fn create_or_get_customer(
        &self,
        idempotency_key: &str,
        user_id: &Uuid,
        email: &str,
        name: Option<&str>,
        existing_customer_id: Option<&str>,
    ) -> Result<stripe_types::Customer, StripeServiceError> {
        // If we have an existing customer ID, try to retrieve it first
        if let Some(customer_id) = existing_customer_id {
            match self.get_customer(customer_id).await {
                Ok(customer) => return Ok(customer),
                Err(e) => {
                    warn!("Failed to retrieve existing customer {}: {}", customer_id, e);
                }
            }
        }

        // Create new customer using direct API call with idempotency key
        let mut customer_data = serde_json::json!({
            "email": email
        });
        
        if let Some(name_value) = name {
            customer_data["name"] = serde_json::Value::String(name_value.to_string());
        }
        
        // Add metadata
        customer_data["metadata[user_id]"] = serde_json::Value::String(user_id.to_string());
        customer_data["metadata[created_by]"] = serde_json::Value::String("vibe_manager".to_string());
        
        let response = self.make_stripe_request_with_idempotency(
            reqwest::Method::POST,
            "customers",
            Some(customer_data),
            idempotency_key,
        ).await?;
        
        // Parse the response into a Customer struct
        let customer: stripe_types::Customer = serde_json::from_value(response)
            .map_err(|e| StripeServiceError::Configuration(format!("Failed to parse customer response: {}", e)))?;
        
        info!("Created Stripe customer: {} for user: {}", customer.id, user_id);
        
        Ok(customer)
    }

    /// Retrieve a customer by ID
    pub async fn get_customer(&self, customer_id: &str) -> Result<stripe_types::Customer, StripeServiceError> {
        let response = self.make_stripe_request_with_idempotency(
            reqwest::Method::GET,
            &format!("customers/{}", customer_id),
            None,
            &format!("get_customer_{}", uuid::Uuid::new_v4()),
        ).await?;
        let customer: stripe_types::Customer = serde_json::from_value(response)
            .map_err(|e| StripeServiceError::Configuration(format!("Failed to parse customer response: {}", e)))?;
        Ok(customer)
    }

    /// Create a payment intent for processing payments
    pub async fn create_payment_intent(
        &self,
        idempotency_key: &str,
        customer_id: &str,
        amount_cents: i64,
        currency: &str,
        description: &str,
        metadata: HashMap<String, String>,
        save_payment_method: bool,
    ) -> Result<stripe_types::PaymentIntent, StripeServiceError> {
        // Create payment intent using direct API call with idempotency key
        let mut payment_data = serde_json::json!({
            "amount": amount_cents,
            "currency": currency.to_lowercase(),
            "customer": customer_id,
            "confirmation_method": "automatic"
        });
        
        if let Some(desc) = Option::from(description) {
            payment_data["description"] = serde_json::Value::String(desc.to_string());
        }
        
        // Add metadata
        for (key, value) in metadata {
            payment_data[format!("metadata[{}]", key)] = serde_json::Value::String(value);
        }
        
        if save_payment_method {
            payment_data["setup_future_usage"] = serde_json::Value::String("off_session".to_string());
        }
        
        let response = self.make_stripe_request_with_idempotency(
            reqwest::Method::POST,
            "payment_intents",
            Some(payment_data),
            idempotency_key,
        ).await?;
        
        // Parse the response into a PaymentIntent struct
        let payment_intent: stripe_types::PaymentIntent = serde_json::from_value(response)
            .map_err(|e| StripeServiceError::Configuration(format!("Failed to parse payment intent response: {}", e)))?;
        
        info!("Created PaymentIntent: {} for customer: {}", payment_intent.id, customer_id);
        Ok(payment_intent)
    }


    /// Create billing portal session for customer self-service
    /// This is the primary method for complex billing operations
    pub async fn create_billing_portal_session(
        &self,
        idempotency_key: &str,
        customer_id: &str,
        return_url: &str,
    ) -> Result<stripe_types::BillingPortalSession, StripeServiceError> {
        // Create billing portal session using direct API call with idempotency key
        let session_data = serde_json::json!({
            "customer": customer_id,
            "return_url": return_url
        });
        
        let response = self.make_stripe_request_with_idempotency(
            reqwest::Method::POST,
            "billing_portal/sessions",
            Some(session_data),
            idempotency_key,
        ).await?;
        
        // Parse the response into a BillingPortalSession struct
        let session: stripe_types::BillingPortalSession = serde_json::from_value(response)
            .map_err(|e| StripeServiceError::Configuration(format!("Failed to parse billing portal session response: {}", e)))?;
        
        info!("Created billing portal session for customer: {}", customer_id);
        Ok(session)
    }

    /// Retrieve a PaymentIntent by ID
    pub async fn get_payment_intent(&self, payment_intent_id: &str) -> Result<stripe_types::PaymentIntent, StripeServiceError> {
        let response = self.make_stripe_request_with_idempotency(
            reqwest::Method::GET,
            &format!("payment_intents/{}", payment_intent_id),
            None,
            &format!("get_payment_intent_{}", uuid::Uuid::new_v4()),
        ).await?;
        let payment_intent: stripe_types::PaymentIntent = serde_json::from_value(response)
            .map_err(|e| StripeServiceError::Configuration(format!("Failed to parse payment intent response: {}", e)))?;
        Ok(payment_intent)
    }



    

    /// List payment methods for a customer from Stripe
    pub async fn list_payment_methods(&self, customer_id: &str) -> Result<Vec<stripe_types::PaymentMethod>, StripeServiceError> {
        let response = self.make_stripe_request_with_idempotency(
            reqwest::Method::GET,
            &format!("payment_methods?customer={}&type=card", customer_id),
            None,
            &format!("list_payment_methods_{}", uuid::Uuid::new_v4()),
        ).await?;
        
        let payment_methods_list: stripe_types::PaymentMethodList = serde_json::from_value(response)
            .map_err(|e| StripeServiceError::Configuration(format!("Failed to parse payment methods response: {}", e)))?;
        
        info!("Retrieved {} payment methods for customer: {}", payment_methods_list.data.len(), customer_id);
        
        Ok(payment_methods_list.data)
    }

    /// List invoices for a customer from Stripe
    pub async fn list_invoices(&self, customer_id: &str) -> Result<Vec<stripe_types::Invoice>, StripeServiceError> {
        let response = self.make_stripe_request_with_idempotency(
            reqwest::Method::GET,
            &format!("invoices?customer={}&limit=100", customer_id),
            None,
            &format!("list_invoices_{}", uuid::Uuid::new_v4()),
        ).await?;
        
        let invoices_list: stripe_types::InvoiceList = serde_json::from_value(response)
            .map_err(|e| StripeServiceError::Configuration(format!("Failed to parse invoices response: {}", e)))?;
        
        info!("Retrieved {} invoices for customer: {}", invoices_list.data.len(), customer_id);
        
        Ok(invoices_list.data)
    }

    /// List invoices for a customer from Stripe with status filter and pagination
    pub async fn list_invoices_with_filter(&self, customer_id: &str, status: Option<&str>, limit: Option<u64>, starting_after: Option<&str>) -> Result<stripe_types::InvoiceList, StripeServiceError> {
        let mut query_params = vec![
            ("customer".to_string(), customer_id.to_string()),
        ];
        
        if let Some(limit_val) = limit {
            query_params.push(("limit".to_string(), limit_val.to_string()));
        }
        
        if let Some(starting_after_value) = starting_after {
            query_params.push(("starting_after".to_string(), starting_after_value.to_string()));
        }
        
        if let Some(status_str) = status {
            query_params.push(("status".to_string(), status_str.to_string()));
        }
        
        let query_string = query_params
            .into_iter()
            .map(|(k, v)| format!("{}={}", k, v))
            .collect::<Vec<_>>()
            .join("&");
        
        let response = self.make_stripe_request_with_idempotency(
            reqwest::Method::GET,
            &format!("invoices?{}", query_string),
            None,
            &format!("list_invoices_filtered_{}", uuid::Uuid::new_v4()),
        ).await?;
        
        let invoices_list: stripe_types::InvoiceList = serde_json::from_value(response)
            .map_err(|e| StripeServiceError::Configuration(format!("Failed to parse invoices response: {}", e)))?;
        
        info!("Retrieved {} invoices for customer: {} with pagination (limit: {:?}, starting_after: {:?})", invoices_list.data.len(), customer_id, limit, starting_after);
        
        Ok(invoices_list)
    }

    /// Detach/delete a payment method in Stripe
    pub async fn detach_payment_method(&self, idempotency_key: &str, payment_method_id: &str) -> Result<stripe_types::PaymentMethod, StripeServiceError> {
        // Detach payment method using direct API call with idempotency key
        let response = self.make_stripe_request_with_idempotency(
            reqwest::Method::POST,
            &format!("payment_methods/{}/detach", payment_method_id),
            None, // POST /v1/payment_methods/:id/detach doesn't require body data
            idempotency_key,
        ).await?;
        
        // Parse the response into a PaymentMethod struct
        let payment_method: stripe_types::PaymentMethod = serde_json::from_value(response)
            .map_err(|e| StripeServiceError::Configuration(format!("Failed to parse payment method response: {}", e)))?;
        
        info!("Detached payment method: {}", payment_method_id);
        Ok(payment_method)
    }

    /// Set default payment method for a customer in Stripe
    pub async fn set_default_payment_method(&self, idempotency_key: &str, customer_id: &str, payment_method_id: &str) -> Result<stripe_types::Customer, StripeServiceError> {
        // Set default payment method using direct API call with idempotency key
        let update_data = serde_json::json!({
            "invoice_settings[default_payment_method]": payment_method_id
        });
        
        let response = self.make_stripe_request_with_idempotency(
            reqwest::Method::POST,
            &format!("customers/{}", customer_id),
            Some(update_data),
            idempotency_key,
        ).await?;
        
        // Parse the response into a Customer struct
        let customer: stripe_types::Customer = serde_json::from_value(response)
            .map_err(|e| StripeServiceError::Configuration(format!("Failed to parse customer response: {}", e)))?;
        info!("Set default payment method {} for customer: {}", payment_method_id, customer_id);
        
        Ok(customer)
    }

    /// Create a product and price (for credit purchases and one-time payments)
    pub async fn create_product_and_price(
        &self,
        idempotency_key: &str,
        product_name: &str,
        price_amount: i64,
        currency: &str,
        interval: Option<&str>,
    ) -> Result<(stripe_types::Product, stripe_types::Price), StripeServiceError> {
        // Create product using direct API call with idempotency key
        let product_data = serde_json::json!({
            "name": product_name,
            "type": "service"
        });
        
        let product_response = self.make_stripe_request_with_idempotency(
            reqwest::Method::POST,
            "products",
            Some(product_data),
            &format!("{}_product", idempotency_key),
        ).await?;
        
        let product: stripe_types::Product = serde_json::from_value(product_response)
            .map_err(|e| StripeServiceError::Configuration(format!("Failed to parse product response: {}", e)))?;
        
        // Create price using direct API call with idempotency key
        let mut price_data = serde_json::json!({
            "currency": currency.to_lowercase(),
            "product": product.id,
            "unit_amount": price_amount
        });
        
        // Add recurring information only if interval is provided (recurring credit plans)
        if let Some(recurring_interval) = interval {
            price_data["recurring[interval]"] = serde_json::Value::String(recurring_interval.to_string());
        }
        
        let price_response = self.make_stripe_request_with_idempotency(
            reqwest::Method::POST,
            "prices",
            Some(price_data),
            &format!("{}_price", idempotency_key),
        ).await?;
        
        let price: stripe_types::Price = serde_json::from_value(price_response)
            .map_err(|e| StripeServiceError::Configuration(format!("Failed to parse price response: {}", e)))?;
        
        info!("Created product {} and price {} for {}", product.id, price.id, product_name);
        Ok((product, price))
    }


    /// Create a SetupIntent for saving payment method without charging (required by handlers)
    pub async fn create_setup_intent(
        &self,
        idempotency_key: &str,
        customer_id: &str,
        metadata: HashMap<String, String>,
    ) -> Result<stripe_types::SetupIntent, StripeServiceError> {
        
        // Create setup intent using direct API call with idempotency key
        let mut setup_data = serde_json::json!({
            "customer": customer_id
        });
        
        // Add metadata
        for (key, value) in metadata {
            setup_data[format!("metadata[{}]", key)] = serde_json::Value::String(value);
        }
        
        let response = self.make_stripe_request_with_idempotency(
            reqwest::Method::POST,
            "setup_intents",
            Some(setup_data),
            idempotency_key,
        ).await?;
        
        let setup_intent: stripe_types::SetupIntent = serde_json::from_value(response)
            .map_err(|e| StripeServiceError::Configuration(format!("Failed to parse setup intent response: {}", e)))?;
        
        info!("Created SetupIntent for customer: {}", customer_id);
        Ok(setup_intent)
    }

    /// Create a Stripe Checkout Session (generic for payment and setup modes)
    pub async fn create_checkout_session(
        &self,
        idempotency_key: &str,
        customer_id: &str,
        mode: &str,
        line_items: Option<Vec<stripe_types::CreateCheckoutSessionLineItems>>,
        success_url: &str,
        cancel_url: &str,
        metadata: HashMap<String, String>,
        billing_address_collection: Option<bool>,
        automatic_tax: Option<bool>,
        invoice_creation_enabled: Option<bool>,
        price_data: Option<serde_json::Value>,
    ) -> Result<stripe_types::CheckoutSession, StripeServiceError> {
        // Create checkout session using direct API call with idempotency key
        let mode_str = mode;
        
        let mut session_data = serde_json::json!({
            "customer": customer_id,
            "mode": mode_str,
            "success_url": success_url,
            "cancel_url": cancel_url,
            "currency": "usd"
        });
        
        // Only set line_items for non-Setup modes
        // Setup mode is for saving payment methods and doesn't require line_items
        if mode_str != "setup" {
            if let Some(items) = line_items {
                let mut line_items_array = Vec::new();
                for item in items.iter() {
                    let mut line_item = serde_json::Map::new();
                    if let Some(price) = &item.price {
                        line_item.insert("price".to_string(), serde_json::Value::String(price.clone()));
                    }
                    if let Some(quantity) = item.quantity {
                        line_item.insert("quantity".to_string(), serde_json::Value::Number(serde_json::Number::from(quantity)));
                    }
                    line_items_array.push(serde_json::Value::Object(line_item));
                }
                session_data["line_items"] = serde_json::Value::Array(line_items_array);
            } else if let Some(price_data_value) = price_data {
                // Use price_data when provided instead of price ID
                let mut line_item = serde_json::Map::new();
                line_item.insert("price_data".to_string(), price_data_value);
                line_item.insert("quantity".to_string(), serde_json::Value::Number(serde_json::Number::from(1)));
                session_data["line_items"] = serde_json::Value::Array(vec![serde_json::Value::Object(line_item)]);
            }
        }
        
        match mode_str {
            "payment" => {
                let mut payment_intent_data = serde_json::Map::new();
                
                // Add metadata to payment_intent_data
                if !metadata.is_empty() {
                    let mut metadata_obj = serde_json::Map::new();
                    for (key, value) in &metadata {
                        metadata_obj.insert(key.clone(), serde_json::Value::String(value.clone()));
                    }
                    payment_intent_data.insert("metadata".to_string(), serde_json::Value::Object(metadata_obj));
                }
                
                
                if !payment_intent_data.is_empty() {
                    session_data["payment_intent_data"] = serde_json::Value::Object(payment_intent_data);
                }
            }
            "setup" => {
                if !metadata.is_empty() {
                    let mut setup_intent_data = serde_json::Map::new();
                    let mut metadata_obj = serde_json::Map::new();
                    for (key, value) in &metadata {
                        metadata_obj.insert(key.clone(), serde_json::Value::String(value.clone()));
                    }
                    setup_intent_data.insert("metadata".to_string(), serde_json::Value::Object(metadata_obj));
                    session_data["setup_intent_data"] = serde_json::Value::Object(setup_intent_data);
                }
            }
            _ => {}
        }
        
        // Add billing address collection if specified
        if let Some(collect_billing) = billing_address_collection {
            if collect_billing {
                session_data["billing_address_collection"] = serde_json::Value::String("required".to_string());
            }
        }
        
        // Add automatic tax if specified
        if let Some(auto_tax) = automatic_tax {
            if auto_tax {
                let mut automatic_tax_obj = serde_json::Map::new();
                automatic_tax_obj.insert("enabled".to_string(), serde_json::Value::Bool(true));
                session_data["automatic_tax"] = serde_json::Value::Object(automatic_tax_obj);
            }
        }
        
        // Add invoice creation if enabled for payment mode
        if mode_str == "payment" {
            if let Some(true) = invoice_creation_enabled {
                let mut invoice_creation = serde_json::Map::new();
                invoice_creation.insert("enabled".to_string(), serde_json::Value::Bool(true));
                session_data["invoice_creation"] = serde_json::Value::Object(invoice_creation);
            }
        }
        
        let response = self.make_stripe_request_with_idempotency(
            reqwest::Method::POST,
            "checkout/sessions",
            Some(session_data),
            idempotency_key,
        ).await?;
        
        // Parse the response into a CheckoutSession struct
        let session: stripe_types::CheckoutSession = serde_json::from_value(response)
            .map_err(|e| StripeServiceError::Configuration(format!("Failed to parse checkout session response: {}", e)))?;
        
        info!("Created Checkout Session: {} for customer: {}", session.id, customer_id);
        Ok(session)
    }

    /// Get a checkout session by ID
    pub async fn get_checkout_session(&self, session_id: &str) -> Result<stripe_types::CheckoutSession, StripeServiceError> {
        let response = self.make_stripe_request_with_idempotency(
            reqwest::Method::GET,
            &format!("checkout/sessions/{}", session_id),
            None,
            &format!("get_checkout_session_{}", uuid::Uuid::new_v4()),
        ).await?;
        let session: stripe_types::CheckoutSession = serde_json::from_value(response)
            .map_err(|e| StripeServiceError::Configuration(format!("Failed to parse checkout session response: {}", e)))?;
        Ok(session)
    }

    /// Create and immediately pay an invoice for auto top-off
    pub async fn create_and_pay_invoice(
        &self,
        idempotency_key: &str,
        customer_id: &str,
        amount_cents: i64,
        currency: &str,
        description: &str,
    ) -> Result<stripe_types::Invoice, StripeServiceError> {
        info!("Creating and paying invoice for customer: {} with amount: {} {}", customer_id, amount_cents, currency);
        
        // First, create an invoice item
        let invoice_item_data = serde_json::json!({
            "customer": customer_id,
            "amount": amount_cents,
            "currency": currency.to_lowercase(),
            "description": description,
        });

        let _invoice_item = self.make_stripe_request_with_idempotency(
            reqwest::Method::POST,
            "invoiceitems",
            Some(invoice_item_data),
            &format!("{}_item", idempotency_key),
        ).await?;

        // Create the invoice
        let invoice_data = serde_json::json!({
            "customer": customer_id,
            "auto_advance": true, // Automatically finalize and attempt payment
            "collection_method": "charge_automatically",
            "description": description,
        });

        let invoice_response = self.make_stripe_request_with_idempotency(
            reqwest::Method::POST,
            "invoices",
            Some(invoice_data),
            &format!("{}_invoice", idempotency_key),
        ).await?;

        let invoice_id = invoice_response["id"].as_str()
            .ok_or_else(|| StripeServiceError::Configuration("Invalid invoice response".to_string()))?;

        // Pay the invoice
        let pay_response = self.make_stripe_request_with_idempotency(
            reqwest::Method::POST,
            &format!("invoices/{}/pay", invoice_id),
            Some(serde_json::json!({})),
            &format!("{}_pay", idempotency_key),
        ).await?;

        // Parse the final invoice response
        let invoice: stripe_types::Invoice = serde_json::from_value(pay_response)
            .map_err(|e| StripeServiceError::Configuration(format!("Failed to parse invoice response: {}", e)))?;

        info!("Successfully created and paid invoice: {} for customer: {}", invoice.id, customer_id);
        Ok(invoice)
    }


}

